version: '3.4'

networks:
  jellyfin:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: "172.23.0.0/16"

services:
  jellyfin:
    container_name: jellyfin
    image: jellyfin/jellyfin
    restart: always
    networks:
      - jellyfin 
    environment: 
      - JELLYFIN_CACHE_DIR=/var/cache/jellyfin
      - JELLYFIN_CONFIG_DIR=/etc/jellyfin
      - JELLYFIN_DATA_DIR=/var/lib/jellyfin
      - JELLYFIN_LOG_DIR=/var/log/jellyfin 
    volumes:
      - /home/jellyfin/jelly-root/config:/etc/jellyfin
      - /home/jellyfin/jelly-root/cache:/var/cache/jellyfin
      - /home/jellyfin/jelly-root/lib:/var/lib/jellyfin
      - /var/log/jellyfin:/var/log/jellyfin
      - ${DOWNLOADS_FOLDER}:/media/Downloads
      - ${VIDEOS_FOLDER}:/media/Videos
      - ${MUSIC_FOLDER}:/home/lms/Music
    devices:
      - /dev/dri/renderD128:/dev/dri/renderD128
      - /dev/dri/card0:/dev/dri/card0
    ports:
      - 8096:8096
  flaresolverr:
    image:   ghcr.io/flaresolverr/flaresolverr:latest 
    networks:
      - jellyfin
    ports: 
      - "8191:8191"
    container_name: flaresolver 
    restart: always

  jellyseerr:
    image:  fallenbagel/jellyseerr:latest
    container_name: jellyseerr
    networks:
      - jellyfin
    ports: 
      - "5055:5055"
    environment:
      TZ: "Europe/Zurich"
      LOG_LEVEL: "debug"
    restart: always
    volumes:
      - /home/jellyfin/jellyseerr:/app/config
  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    networks:
      - jellyfin
    container_name: bazarr
    environment:
      - PUID=1024
      - PGID=100
      - TZ=Europe/Zurich
    volumes:
      - /home/jellyfin/bazarr/data/config:/config
      - ${TV_SHOWS_FOLDER}:/tv
      - ${MOVIES_FOLDER}:/movies
    ports:
      - 6767:6767
    restart: always
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    networks:
      - jellyfin
    environment:
      - PUID=1024
      - PGID=100
      - TZ=Europe/Zurich
    volumes:
      - /home/jellyfin/sonarr/config:/config
      - ${TV_SHOWS_FOLDER}:/tv 
      - ${SONARR_FOLDER}:/downloads
    ports:
      - 8989:8989
    restart: always  

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:develop
    container_name: prowlarr
    networks:
      - jellyfin
    environment:
      - PUID=1024
      - PGID=100
      - TZ=Europe/Zurich
    volumes:
      - ${PROWLARR_CONFIG_FOLDER}:/config
    ports:
      - 9696:9696
    restart: always
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    networks:
      - jellyfin
    environment:
      - PUID=1024
      - PGID=100
      - TZ=Europe/Zurich
    volumes:
      - /home/jellyfin/radarr/config:/config
      - ${RADARR_FOLDER}:/downloads
      - ${MOVIES_FOLDER}:/movies 
    ports:
      - 7878:7878
    restart: always
